### ISSUE TITLE
Multipatch volume changes

### ISSUE THREAD

**Issue by michelkeijzers** [DaBlick/PCG-Tools#2]
By default all volumes of programs/combis and or set list slots are set to 127. This means there is no headroom left.

It would be nice if there is a way to select a group of programs, combis or set list slots, and change the volume of all of these by a fixed amount or a percentage.

For Kronos, the easiest is to change the set list slots, for other models combi. Changing program values can be tricky because this parameter is not supported by PCG Tools yet and differs from model to model.

**Comment by DaBlick** [comment]
Michael.  This is now implement and can be closed right?  But I don’t think you pushed your changes to GitHub.

**Comment by michelkeijzers** [comment]
Hello David,

Yes you are right ... I tried to push/commit the changes, but I found out my personal GitHub was connected somehow, so I have to find my local repository (or clone yours again) and try it again. But I didn't have time yesterday (neither today and tomorrow, so I will do this weekend).

Also I found out sadly I only have an older version of the word document of the manual, and not a recent, so if I want to update the manual I also have some work. I'm also intending to add some of the documentation to Git (I didn't do that so far because in that folder is some NDA info which I need to remove before commiting to GitHub).

On the other hand, nobody so far changed something so it's mostly for myself (and you possibly) to have GitHub updated.

Kind regards and thanks for the help with GitHub.

Michel

________________________________
Van: Dave Blickstein <notifications@github.com>
Verzonden: woensdag 28 augustus 2019 10:39
Aan: DaBlick/PCG-Tools <PCG-Tools@noreply.github.com>
CC: Michel Keijzers <michelkeijzers@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DaBlick/PCG-Tools] Multipatch volume changes (#2)


Michael. This is now implement and can be closed right? But I don’t think you pushed your changes to GitHub.

**Comment by DaBlick** [comment]
OK.      If you need help with any of the git stuff, let me know.

**Comment by michelkeijzers** [comment]
Thanks David,

I will first try myself.

Maybe I don't have a local git repository anymore. Can I clone it, overwrite the changed files in the local git repository and than push it to your remote repository?

Kind regards,

Michel

________________________________
Van: Dave Blickstein <notifications@github.com>
Verzonden: woensdag 28 augustus 2019 12:50
Aan: DaBlick/PCG-Tools <PCG-Tools@noreply.github.com>
CC: Michel Keijzers <michelkeijzers@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DaBlick/PCG-Tools] Multipatch volume changes (#2)

OK. If you need help with any of the git stuff, let me know.

**Comment by DaBlick** [comment]
I think what you probably wanna do is this:


   1. Find your old clone of the repo, or make a new clone
   2. You copy copy (only) the files you changed into the clone.   I think
   you could get into trouble if you try to copy everything  because there's a
   good chance git will see "everything"  as having been changed.
   3. Commit the changes.
   4. Push them.

If there's any trouble let me now.

FWIW, a very very nice tool for using git is SourceTree by Atlassian.
 It's entirely free, and what makes it nice is that IMHO, while it's FAR
from the most fully-featured GUI git tool, it is perhaps the most
user-friendly.    I'd highly recommend it, and you may well find that you
use it to do other than push/pull/commit.   I find it handy for reverting
changes I've made that I've later decided against because whereas IDE's
know how to do stuff like "undo",  SourceTree (via git) will allow you to
undo sections, and undo them out of the original order you did them in.
 So if I make changes A, B and then C.... and then I want to undo (just) A,
you're out of luck with something like "undo", but it's utterly trivial
(and obvious) with SourceTree.

What I'm saying is that git and SourceTree are part of my editing operation
even aside from the operations you usually think of with stuff like CVS and
SVN.

Git really is quite different than SVN.        It's very easy to think of
git vs svn as "Coke vs Pepsi".  In my opinion that would be wrong.

          db

**Comment by DaBlick** [comment]
Michael, as I'm so grateful for the value you've provided with PCG Tools,
if you need help with any of the git stuff, I would be quite happy to
arrange a time where we do a screenshare and chat and give you some help,
perhaps a tour of SourceTree, etc.

**Comment by michelkeijzers** [comment]
Hello David,

Thanks for that application name ... I will try it too. However, I prefer the builtin GIT connection with Visual Studio (works very easy). It's just that I"m also doing another  project using VS and it was connected to my own repo even while I opened PCG Tools. Probably I can just change it.

At my work we now also use Git, although it has it's own simplified Git connection (inside Eclipse).

I have more experience with other types, like Clearcase (which looks like SVN probably, but SVN is really long time ago). ClearCase I know very well, although the company I worked for has a complicated layer around it. Their code base was so big they had to slice it into smaller parts (something like 100M lines of code if I remember right).

I will first try some things myself, but maybe I could use some help later. Thanks for the offer anyway.

Kind regards,

Michel

________________________________
Van: Dave Blickstein <notifications@github.com>
Verzonden: woensdag 28 augustus 2019 13:51
Aan: DaBlick/PCG-Tools <PCG-Tools@noreply.github.com>
CC: Michel Keijzers <michelkeijzers@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DaBlick/PCG-Tools] Multipatch volume changes (#2)

I think what you probably wanna do is this:


1. Find your old clone of the repo, or make a new clone
2. You copy copy (only) the files you changed into the clone. I think
you could get into trouble if you try to copy everything because there's a
good chance git will see "everything" as having been changed.
3. Commit the changes.
4. Push them.

If there's any trouble let me now.

FWIW, a very very nice tool for using git is SourceTree by Atlassian.
It's entirely free, and what makes it nice is that IMHO, while it's FAR
from the most fully-featured GUI git tool, it is perhaps the most
user-friendly. I'd highly recommend it, and you may well find that you
use it to do other than push/pull/commit. I find it handy for reverting
changes I've made that I've later decided against because whereas IDE's
know how to do stuff like "undo", SourceTree (via git) will allow you to
undo sections, and undo them out of the original order you did them in.
So if I make changes A, B and then C.... and then I want to undo (just) A,
you're out of luck with something like "undo", but it's utterly trivial
(and obvious) with SourceTree.

What I'm saying is that git and SourceTree are part of my editing operation
even aside from the operations you usually think of with stuff like CVS and
SVN.

Git really is quite different than SVN. It's very easy to think of
git vs svn as "Coke vs Pepsi". In my opinion that would be wrong.

db

**Comment by DaBlick** [comment]
One thing to note, is that each GUI git tool (be it a separate tool or some
sort of IDE feature/plugin) has its own set of strengths and advantages.
One nice thing to leverage however, is that you can use ALL of them for any
one project.

I tend to do most git operations in my IDE (JetBrains IntelliJ) but for for
certain things which SourceTree excels at I use SourceTree.  I also use
something called Sublime Merge and another things called SmartGit for
specific things that those do well

I have used ClearCase, Perforce, CSV, SVN, and a few Digital Equipment Corp
tools you've not likely heard of.     Used ClearCase extensively because
that's what Sun used to do the Java JVM and JRE which I worked on.
 ClearCase's diff engime is unparalleled at AVOIDING merge conflicts IMHO.
 That's what made it a good choice for the Java platform which is licensed
to 100s of licensees who have to take "drops" from Sun and merge in their
changes.

However, I will tell you this....

Git is so DIFFERENT and so superior (IMHO) that I personally would HATE to
ever have to NOT use it.   In fact, at my last job, I was forbidden from
using it (they used SVN) and I used it secretly by using a git-to-SVN
bridge, so I could do all the git things I've just become dependent on on a
DAILY basis like staging, something called "hunks", lightweight branching,
offline working, etc.

Sometimes git is hard to get used to, but almost everyone I've trained
ended up loving it once they STOPPED thinking it as "Coke vs Pepsi" for
Source Control.    Git really is a very different paradigm for source
control.


      db

**Comment by michelkeijzers** [comment]
Hello Dave,

I think I have a problem. .I haven't installed SourceTree yet (I will do that after I fix the main problem).

I cloned the repository. Than I overwrote all files (since I changed the copyright year it didn't matter much to do some intelligent diff). So far so good.
However, then I added the documentation folder. It contained a 180 MB big doc file (an older manual file). I committed everything to my local repository. Then when I wanted to sync, I got an error that a GitHub repository is only allowed to be 100 MB.

I tried removing the file but in the local git administration I think the file is already included. Is there a way to remove a local git commit?

Kind regards,

Michel

________________________________
Van: Dave Blickstein <notifications@github.com>
Verzonden: woensdag 28 augustus 2019 14:24
Aan: DaBlick/PCG-Tools <PCG-Tools@noreply.github.com>
CC: Michel Keijzers <michelkeijzers@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DaBlick/PCG-Tools] Multipatch volume changes (#2)

One thing to note, is that each GUI git tool (be it a separate tool or some
sort of IDE feature/plugin) has its own set of strengths and advantages.
One nice thing to leverage however, is that you can use ALL of them for any
one project.

I tend to do most git operations in my IDE (JetBrains IntelliJ) but for for
certain things which SourceTree excels at I use SourceTree. I also use
something called Sublime Merge and another things called SmartGit for
specific things that those do well

I have used ClearCase, Perforce, CSV, SVN, and a few Digital Equipment Corp
tools you've not likely heard of. Used ClearCase extensively because
that's what Sun used to do the Java JVM and JRE which I worked on.
ClearCase's diff engime is unparalleled at AVOIDING merge conflicts IMHO.
That's what made it a good choice for the Java platform which is licensed
to 100s of licensees who have to take "drops" from Sun and merge in their
changes.

However, I will tell you this....

Git is so DIFFERENT and so superior (IMHO) that I personally would HATE to
ever have to NOT use it. In fact, at my last job, I was forbidden from
using it (they used SVN) and I used it secretly by using a git-to-SVN
bridge, so I could do all the git things I've just become dependent on on a
DAILY basis like staging, something called "hunks", lightweight branching,
offline working, etc.

Sometimes git is hard to get used to, but almost everyone I've trained
ended up loving it once they STOPPED thinking it as "Coke vs Pepsi" for
Source Control. Git really is a very different paradigm for source
control.


db

**Comment by DaBlick** [comment]
Hmmm..... there is a way to remove a file from source control, but the
thing is that the "history" stays.  Git never "deletes" anything unless you
use a fairly heavy hammer command - this is so you can always get back to
some committed state you were previously in no matter what.

However,, you may need to use a heavy hammer command.     For now, I'd try
the "shallow prune" method described in this article:
https://www.atlassian.com/blog/git/handle-big-repositories-git

Don't worry about the warnings about having to "reclone".   I have a local
clone, but I think I'm the only one and I can easily reclone.

If that doesn't work, you might want to try the LFS approach they describe
later in the article.

Now Michael, I won't tell you to just RTFM here and leave you on your own.
 If you need help, even like a screen-sharing session, I'm willing to do
that.   I'm the guy that asked you to put the sources up on Github and I'm
grateful to you for doing that (even you if you just added the one thing I
was thinking of doing :-) ) .    So, have a look through the article and if
you just don't wanna be bothered with all this, let me know and perhaps we
can arrange a screenshare.

Thanks.

         Dave

**Comment by DaBlick** [comment]
LFS docs - note how simple it is:   https://git-lfs.github.com/

**Comment by michelkeijzers** [comment]
Hello Dave,

Thanks for your extensive reply. Sadly, the first link does not open (handling big repositories). But the article about pruning did. I think that is exactly what I need, however, I could not find the Prune command within VS. 

However, I managed to  commit/push everything to the develop branch, by harshly removing my local git with the 'problematic big file', and just overwrote the files again after doing a new clone (I also couldn't find the Reclone command). But now everything seems to work again.

Just an additional question (you don't have to answer if it takes too much time)... Is there an easy way to see how much MB our GIT repository is? My local directory (with all files + git) is 220 MB, but the 
.git directory is 35 MB so that's ok. 

I don't think a sharing session is not needed (although I gladly keep the invitation in case it's needed in the future). 

Btw, maybe I'm going to do another commit for the updated manual.

Kind regards,

Michel

**Comment by michelkeijzers** [comment]
Hello Dave,

I think my last emails might not have reached you.

I read/scanned through the documents and it seemed that purge would be the best solution. However, I could not find that option within VS 2019.

So I used another harsh method but it worked well: I removed my local repository, cloned again your githib PCG Tools repository, and copied my changes over. I changed the copyright year so almost all files changed.

Today I updated the manual and also put it into github without any problem. I hope I don't get in trouble in the future if the max. amount of GitHub is 100 MB (because the manual itself is more than 10 MB).

Thanks for all help so far. For now I don't need any screen sharing session because I assume it's working now (all is stored ok in GitHub). In the future I will always get it from GitHub before I start doing something.

If you want I can also add your name into PCG Tools (for the next release, so can take some time).

Kind regards,

Michel

________________________________
Van: Dave Blickstein <notifications@github.com>
Verzonden: zaterdag 31 augustus 2019 14:33
Aan: DaBlick/PCG-Tools <PCG-Tools@noreply.github.com>
CC: Michel Keijzers <michelkeijzers@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DaBlick/PCG-Tools] Multipatch volume changes (#2)

LFS docs - note how simple it is: https://git-lfs.github.com/

**Comment by DaBlick** [comment]
Michel,

Apologies again for the lack of responsiveness    I had a gig this weekend
and I was extremely busy learning and configuring our new digital mixer.
I'm really the only tech-oriented guy in this band so it fell to me.

I think your solution was a good way to do it.

As for adding my name, while I'd of course have no objection, I also don't
feel like I deserve the credit really.  I'll leave it up to you.   I
appreciate the offer in any case.

Let me know if you need any help in the future with the git stuff.

         db

**Comment by michelkeijzers** [comment]
Hello Dave,

You don't have to apologize for having no time, I have also not much time at some times.

We also have a digital mixer since half a year (Soundcraft SI Expression) including in-ear system. Although I'm also the most technical guy, there is another one who also knows about mixing so he mostly does that part. Although I know a bit how it works too.

Instead, I'm handling the lights. So far it's not that much, but I'm trying (for quite some time) to create a device to control the lights based on MIDI. There are already solutions, but either they are very expensive, or not flexible. I want eventually to be able to control it fully from my Kronos (and pedal board), based on set list slot, but also MIDI notes, CC values and later external sensors maybe. Since I'm fully new to electronics (well I was), it's quite a learning experience.

For the next release I will add your name (but it can take some time, maybe a year or so like last time, sorry for that). Maybe I can add a link to your band name (if you tell me where I can find it).

Kind regards,

Michel

________________________________
Van: Dave Blickstein <notifications@github.com>
Verzonden: dinsdag 3 september 2019 03:25
Aan: DaBlick/PCG-Tools <PCG-Tools@noreply.github.com>
CC: Michel Keijzers <michelkeijzers@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DaBlick/PCG-Tools] Multipatch volume changes (#2)

Michel,

Apologies again for the lack of responsiveness I had a gig this weekend
and I was extremely busy learning and configuring our new digital mixer.
I'm really the only tech-oriented guy in this band so it fell to me.

I think your solution was a good way to do it.

As for adding my name, while I'd of course have no objection, I also don't
feel like I deserve the credit really. I'll leave it up to you. I
appreciate the offer in any case.

Let me know if you need any help in the future with the git stuff.

db

**Comment by DaBlick** [comment]
Michael,

I actually find it FUN to work with this mixer.    I just  love that it
provides so much capability beyond what I've experienced for 40 years
playing in bars and small clubs, and that it does it all in a package
that's actually smaller and easier to setup than what we used to do with
analog mixers.

I actually play in so many bands that I wouldn't really want a link to any
particular one of them.    I don't have a website for myself as a musician,
so what I'd like to use for a link is my Facebook page:
https://www.facebook.com/DaveBlickstein/

Thanks

       db

**Comment by michelkeijzers** [comment]
Hello Dave,

I'm glad you like it ...actually, I haven't used the volume mixer myself (yet), because so far I did it by hand, but I regularly get into the max. 127 volume problem.

I wish Korg would implement this on the Kronos itself, but I think that of many features of PCG Tools. It sounds strange, but I wish PCG Tools would not be necessary, because it could be done on the Kronos directly.

I will add your link, however, hope you don't mind to wait a bit, because I don't have a release planned. Although adding the link only takes 15 minutes, making a release takes several hours, so I rather combine it in case I have another feature or bug fix. I hope you understand this.

Everything is now in Git, so thanks for the help.

Kind regards,

Michel
________________________________
Van: Dave Blickstein <notifications@github.com>
Verzonden: dinsdag 10 september 2019 02:41
Aan: DaBlick/PCG-Tools <PCG-Tools@noreply.github.com>
CC: Michel Keijzers <michelkeijzers@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DaBlick/PCG-Tools] Multipatch volume changes (#2)

Michael,

I actually find it FUN to work with this mixer. I just love that it
provides so much capability beyond what I've experienced for 40 years
playing in bars and small clubs, and that it does it all in a package
that's actually smaller and easier to setup than what we used to do with
analog mixers.

I actually play in so many bands that I wouldn't really want a link to any
particular one of them. I don't have a website for myself as a musician,
so what I'd like to use for a link is my Facebook page:
https://www.facebook.com/DaveBlickstein/

Thanks

db

**Comment by DaBlick** [comment]
Ugh... was hoping to get around to finishing the comped version as impute
for you.

I have another project going on with a deadline and the singer just sent me
his tracks.    He’s kinda a difficult guy and he didn’t listen to my advice
about monitoring and (even he admits) that his pitching is just way way off.

So... I’m going to be spending the entire afternoon with Melodyne (pitch
correction plugin)  :-)

Hopefully I’ll STILL get to it this weekend.   We are close to wrapping
that project up and if so, I’ll have wrapped 3 projects in one week!
 Kinda anxious to get onto newer things.

I’ll keep you posted.

     Db

**Comment by DaBlick** [comment]
No worries! Thanks for the update. Enjoy the weekend LouSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Dave Blickstein <dablick@gmail.com> Date: 8/22/20  1:55 PM  (GMT-05:00) To: DaBlick/PCG-Tools <reply@reply.github.com>, lucien2112 <lucien2112@aol.com> Subject: Re: doctor drums Ugh... was hoping to get around to finishing the comped version as impute for you.I have another project going on with a deadline and the singer just sent me his tracks.    He’s kinda a difficult guy and he didn’t listen to my advice about monitoring and (even he admits) that his pitching is just way way off.So... I’m going to be spending the entire afternoon with Melodyne (pitch correction plugin)  :-)Hopefully I’ll STILL get to it this weekend.   We are close to wrapping that project up and if so, I’ll have wrapped 3 projects in one week!    Kinda anxious to get onto newer things.I’ll keep you posted.     DbOn Mon, Aug 10, 2020 at 12:00 PM lucien2112 <lucien2112@aol.com> wrote:I do see this as a collab...lol..thought my drums were ready for next step,  but your notes on things to change tells me I'm not playing things the collab will accept as final drumming yet. So I need to know what will be ok before I lay down a track .It's a great rendition and fun.Just not getting the vibe my tracks will be accepted the way I'm doing them now.Just dont want to make a ton of changes after the fact. Drums should typically be finals when at this stage.Sent from my Verizon, Samsung Galaxy smartphone-------- Original message --------From: Dave Blickstein <dablick@gmail.com> Date: 8/10/20  11:42 AM  (GMT-04:00) To: lucien2112 <lucien2112@aol.com> Subject: Re: doctor drums I'll try to assemble a cohesive complete set of notes, and indicate which ones are sorta "please change" and which are "JMHO".    One disconnect we seem to have is that I sorta see this as collaboration, and I gather that you are kind viewing this as "session".   I guess my "thing" is that I want this to be FUN for everyone and for them to feel that it's not "Dave Blickstein Project" but a collaborative effort.I'll try to give you more focused and complete notes going forward.    I hope this hasn't soured you on future collaborations.   On Mon, Aug 10, 2020 at 11:22 AM lucien2112 <lucien2112@aol.com> wrote:Very cool thanks.I do want notes at once but had no idea there were so many changes lol. I as thinking I was alot closer to what you had suggested in your notes so far.Sent from my Verizon, Samsung Galaxy smartphone-------- Original message --------From: Dave Blickstein <dablick@gmail.com> Date: 8/10/20  11:18 AM  (GMT-05:00) To: lucien2112 <lucien2112@aol.com> Subject: Re: doctor drums OK, I had thought that you didn't want a pile of notes all at once.    I had thought, mistakenly, that you preferred an "iterative" approach.I will make an edit, but it will take a few days but it sounds like that works well with your schedule.   On Mon, Aug 10, 2020 at 9:27 AM lucien2112 <lucien2112@aol.com> wrote:Ok, please make an edit out of what you have, with parts or grooves you like.I'm all for making adjustments but seems like with every update you have specific items to address directly that weren't really a topic in a previous demo. It would help me greatly if you could let me know where you want something particular, and where I have some freedom.Happy to make this work but feel a bit like I'm running in a circle on parts now...Fix one, change something else.Let's try to nail down what you want different please.I'll be out teaching until 8pm today Thanks LouSent from my Verizon, Samsung Galaxy smartphone-------- Original message --------From: Dave Blickstein <dablick@gmail.com> Date: 8/10/20  9:17 AM  (GMT-05:00) To: lucien2112 <lucien2112@aol.com> Subject: Re: doctor drums Some more "notes".... all "optional" (up to you):I'm not wild about the crash cymbals in the (example at 1:25).  They seem "too much" and distracting - kinda contrary to the "building" notionI think I want to identify my favorite groove examples from some previous takes.   There's a sorta rhythm implied by the riff (which the violin doubles a lot).   Some of your snare hits seem to come in between the accents in the riff which kinda seems to make it "busy".   I think what I've just figured out is that my favorite grooves are where any snare hits are a) light and basically "double" the accents of the piano and violin - this is a bit vague, but the main groove is defined by the opening piano riff which is pretty much a constant through the entire song.I'll try and get you a sample of the "choke", but in case it might clarify, I think what I'd like at the ending is for the drums to "double" the riff and then do a cymbal choke on the very very last chord that you hear sustaining/decaying after playing stops.           dbOn Sun, Aug 9, 2020 at 11:04 PM <lucien2112@aol.com> wrote: Lol...of course i have stems. I do this professionally as part of my living ;-p Even tho my little studio room is...little...with good mics,drums and software i'm set to give folks high quality pro tracks for mix and release, been at it here for close to 10 yrs w the LAB now. Glad things are looking good for the ideas. Can you just shoot me a sample of the ending choke in the right spot? You don't even need to demo the whole song, just the last few bars if need be, so i can hear right where it's intended. If i do a final version, that would be a full pass at the song. So...i wouldn't be sending you stems for these demo versions...only a final completed version. The kit is 10 mic tracks(or "stems") so you wouldn't be able to comp things from these demos into the final version plus these demos are tracked w reverb...real take would be dry drums for the production to be done my you or whomever is mixing. all i do is have panning on my individual tracks to set the kit correctly in the stereo mix.. You also mentioned likely having video to go with these? I haven't done any video yet, since it was demos, I would video the final tracking session to go with the raw track stems you'd get.I'm quite happy with the drums as is so...good to go if/when you arei see you just sent over a mix..anything i need to reference? something you changed? Lou-----Original Message-----From: Dave Blickstein <dablick@gmail.com>To: lucien2112@aol.comSent: Sun, Aug 9, 2020 10:43 pmSubject: Re: doctor drumsSo I got my ass outta bed and flew it into my session.  Lou, I love it.  I think we're pretty much "there" in terms of grooves arrangement and such.   The choke at the end is indeed not where I had intended it.   I'll describe it this way:  the choke should be on the very last chord.   Which occurs at bar 96 beat 4 (slightly "anticipated").    This is at time stamp 4:31 or so.     I think if you wanna record a final version that might make sense at this point.   I might be inclined to still comp some stuff from previous takes into the final version but I think if you give me a final version of what you have heere, I can probably assemble everything.   Up to you.  I mean, we could away nit pick and what not and do more tuning of things, but I'd be quite happy with what you got here.Do you have stems from each mic?    I think when you send the me the final version, I (of course) would slightly prefer to get stems for each mic so I can balance things in the context of the mix.    (I'm thinking of paying a pro to mix this anyway - I'm now pretty good at the. engineering side, but not so much on the mix side.)So... what do YOU think?   On Sun, Aug 9, 2020 at 10:28 PM David Blickstein <dablick@gmail.com> wrote:I’m listening to drum track in bed.  Sounds great.  At least without hearing it in context I love all the grooves.  Great swing feel.   Can’t wait to fly it into my sesh and hear it in context. ThanksSent from my iPhoneOn Aug 9, 2020, at 9:49 PM, lucien2112@aol.com wrote:﻿Hello, Attached is demo drums V3 also based on latest notes (let me know if you need or want the WAV file, i have that ready to send if need be!)New intro and verse 1 cymbal treatmentNew more "similar to other parts" grooves in versesChoke cymbal at end(tho not 110% sure i did it in the right place!)EnjoyLouP.S.Mp3 file is again exported as same size to your files for line up.<Doctor Drum Demo V3.mp3>
